fail_fast: true

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: detect-private-key
-   repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
        - id: black
-   repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
        - id: flake8
